from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1717, 874)
        MainWindow.setMinimumSize(QtCore.QSize(0, 750))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pasek = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasek.sizePolicy().hasHeightForWidth())
        self.pasek.setSizePolicy(sizePolicy)
        self.pasek.setMinimumSize(QtCore.QSize(72, 0))
        self.pasek.setMaximumSize(QtCore.QSize(72, 16777215))
        self.pasek.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pasek.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pasek.setObjectName("pasek")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pasek)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 8)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.pasek)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(70, 85))
        self.frame.setMaximumSize(QtCore.QSize(70, 85))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_sidebar_zwin = QtWidgets.QPushButton(self.frame)
        self.btn_sidebar_zwin.setGeometry(QtCore.QRect(0, 10, 70, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sidebar_zwin.sizePolicy().hasHeightForWidth())
        self.btn_sidebar_zwin.setSizePolicy(sizePolicy)
        self.btn_sidebar_zwin.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_sidebar_zwin.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_sidebar_zwin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/icons_white/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../icons/icons_blue/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_sidebar_zwin.setIcon(icon)
        self.btn_sidebar_zwin.setIconSize(QtCore.QSize(40, 40))
        self.btn_sidebar_zwin.setCheckable(False)
        self.btn_sidebar_zwin.setObjectName("btn_sidebar_zwin")
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.strona_glowna = QtWidgets.QFrame(self.pasek)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strona_glowna.sizePolicy().hasHeightForWidth())
        self.strona_glowna.setSizePolicy(sizePolicy)
        self.strona_glowna.setMinimumSize(QtCore.QSize(70, 85))
        self.strona_glowna.setMaximumSize(QtCore.QSize(70, 85))
        self.strona_glowna.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.strona_glowna.setFrameShadow(QtWidgets.QFrame.Raised)
        self.strona_glowna.setObjectName("strona_glowna")
        self.btn_strona_glowna = QtWidgets.QPushButton(self.strona_glowna)
        self.btn_strona_glowna.setGeometry(QtCore.QRect(0, 10, 70, 70))
        self.btn_strona_glowna.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_strona_glowna.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_strona_glowna.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/icons_white/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../icons/icons_blue/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_strona_glowna.setIcon(icon1)
        self.btn_strona_glowna.setIconSize(QtCore.QSize(40, 40))
        self.btn_strona_glowna.setCheckable(True)
        self.btn_strona_glowna.setAutoExclusive(True)
        self.btn_strona_glowna.setObjectName("btn_strona_glowna")
        self.grupa_przyciski = QtWidgets.QButtonGroup(MainWindow)
        self.grupa_przyciski.setObjectName("grupa_przyciski")
        self.grupa_przyciski.addButton(self.btn_strona_glowna)
        self.verticalLayout_2.addWidget(self.strona_glowna)
        self.kalendarz = QtWidgets.QFrame(self.pasek)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kalendarz.sizePolicy().hasHeightForWidth())
        self.kalendarz.setSizePolicy(sizePolicy)
        self.kalendarz.setMinimumSize(QtCore.QSize(70, 85))
        self.kalendarz.setMaximumSize(QtCore.QSize(70, 85))
        self.kalendarz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kalendarz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kalendarz.setObjectName("kalendarz")
        self.btn_kalendarz = QtWidgets.QPushButton(self.kalendarz)
        self.btn_kalendarz.setGeometry(QtCore.QRect(0, 10, 70, 70))
        self.btn_kalendarz.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_kalendarz.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_kalendarz.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/icons_white/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../icons/icons_blue/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_kalendarz.setIcon(icon2)
        self.btn_kalendarz.setIconSize(QtCore.QSize(40, 40))
        self.btn_kalendarz.setCheckable(True)
        self.btn_kalendarz.setAutoExclusive(True)
        self.btn_kalendarz.setObjectName("btn_kalendarz")
        self.grupa_przyciski.addButton(self.btn_kalendarz)
        self.verticalLayout_2.addWidget(self.kalendarz)
        spacerItem = QtWidgets.QSpacerItem(67, 177, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.konto = QtWidgets.QFrame(self.pasek)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.konto.sizePolicy().hasHeightForWidth())
        self.konto.setSizePolicy(sizePolicy)
        self.konto.setMinimumSize(QtCore.QSize(70, 85))
        self.konto.setMaximumSize(QtCore.QSize(70, 85))
        self.konto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.konto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.konto.setObjectName("konto")
        self.btn_konto = QtWidgets.QPushButton(self.konto)
        self.btn_konto.setGeometry(QtCore.QRect(0, 10, 70, 70))
        self.btn_konto.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_konto.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_konto.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/icons_white/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("../icons/icons_blue/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_konto.setIcon(icon3)
        self.btn_konto.setIconSize(QtCore.QSize(40, 40))
        self.btn_konto.setCheckable(True)
        self.btn_konto.setAutoExclusive(True)
        self.btn_konto.setObjectName("btn_konto")
        self.grupa_przyciski.addButton(self.btn_konto)
        self.verticalLayout_2.addWidget(self.konto)
        self.ustawienia = QtWidgets.QFrame(self.pasek)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ustawienia.sizePolicy().hasHeightForWidth())
        self.ustawienia.setSizePolicy(sizePolicy)
        self.ustawienia.setMinimumSize(QtCore.QSize(70, 85))
        self.ustawienia.setMaximumSize(QtCore.QSize(70, 85))
        self.ustawienia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ustawienia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ustawienia.setObjectName("ustawienia")
        self.btn_ustawienia = QtWidgets.QPushButton(self.ustawienia)
        self.btn_ustawienia.setGeometry(QtCore.QRect(0, 10, 70, 70))
        self.btn_ustawienia.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_ustawienia.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_ustawienia.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/icons_white/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("../icons/icons_blue/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_ustawienia.setIcon(icon4)
        self.btn_ustawienia.setIconSize(QtCore.QSize(40, 40))
        self.btn_ustawienia.setCheckable(True)
        self.btn_ustawienia.setAutoExclusive(True)
        self.btn_ustawienia.setObjectName("btn_ustawienia")
        self.grupa_przyciski.addButton(self.btn_ustawienia)
        self.verticalLayout_2.addWidget(self.ustawienia)
        self.wyloguj = QtWidgets.QFrame(self.pasek)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wyloguj.sizePolicy().hasHeightForWidth())
        self.wyloguj.setSizePolicy(sizePolicy)
        self.wyloguj.setMinimumSize(QtCore.QSize(70, 85))
        self.wyloguj.setMaximumSize(QtCore.QSize(70, 85))
        self.wyloguj.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wyloguj.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wyloguj.setObjectName("wyloguj")
        self.btn_wyloguj = QtWidgets.QPushButton(self.wyloguj)
        self.btn_wyloguj.setGeometry(QtCore.QRect(0, 10, 70, 70))
        self.btn_wyloguj.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_wyloguj.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_wyloguj.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/icons_white/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("../icons/icons_blue/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_wyloguj.setIcon(icon5)
        self.btn_wyloguj.setIconSize(QtCore.QSize(40, 40))
        self.btn_wyloguj.setCheckable(True)
        self.btn_wyloguj.setAutoExclusive(True)
        self.btn_wyloguj.setObjectName("btn_wyloguj")
        self.grupa_przyciski.addButton(self.btn_wyloguj)
        self.verticalLayout_2.addWidget(self.wyloguj)
        self.horizontalLayout.addWidget(self.pasek, 0, QtCore.Qt.AlignLeft)
        self.pasek_hover = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasek_hover.sizePolicy().hasHeightForWidth())
        self.pasek_hover.setSizePolicy(sizePolicy)
        self.pasek_hover.setMinimumSize(QtCore.QSize(188, 0))
        self.pasek_hover.setMaximumSize(QtCore.QSize(188, 16777215))
        self.pasek_hover.setStyleSheet("")
        self.pasek_hover.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pasek_hover.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pasek_hover.setObjectName("pasek_hover")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pasek_hover)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 8)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.pasek_hover)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(185, 85))
        self.frame_3.setMaximumSize(QtCore.QSize(185, 85))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_sidebar_zwin_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_sidebar_zwin_2.setGeometry(QtCore.QRect(0, 10, 70, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sidebar_zwin_2.sizePolicy().hasHeightForWidth())
        self.btn_sidebar_zwin_2.setSizePolicy(sizePolicy)
        self.btn_sidebar_zwin_2.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_sidebar_zwin_2.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_sidebar_zwin_2.setText("")
        self.btn_sidebar_zwin_2.setIcon(icon)
        self.btn_sidebar_zwin_2.setIconSize(QtCore.QSize(40, 40))
        self.btn_sidebar_zwin_2.setCheckable(False)
        self.btn_sidebar_zwin_2.setObjectName("btn_sidebar_zwin_2")
        self.verticalLayout_4.addWidget(self.frame_3, 0, QtCore.Qt.AlignLeft)
        self.strona_glowna_3 = QtWidgets.QFrame(self.pasek_hover)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strona_glowna_3.sizePolicy().hasHeightForWidth())
        self.strona_glowna_3.setSizePolicy(sizePolicy)
        self.strona_glowna_3.setMinimumSize(QtCore.QSize(185, 85))
        self.strona_glowna_3.setMaximumSize(QtCore.QSize(185, 85))
        self.strona_glowna_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.strona_glowna_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.strona_glowna_3.setObjectName("strona_glowna_3")
        self.btn_strona_glowna_3 = QtWidgets.QPushButton(self.strona_glowna_3)
        self.btn_strona_glowna_3.setGeometry(QtCore.QRect(0, 10, 185, 70))
        self.btn_strona_glowna_3.setMinimumSize(QtCore.QSize(185, 70))
        self.btn_strona_glowna_3.setMaximumSize(QtCore.QSize(185, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_strona_glowna_3.setFont(font)
        self.btn_strona_glowna_3.setIcon(icon1)
        self.btn_strona_glowna_3.setIconSize(QtCore.QSize(40, 40))
        self.btn_strona_glowna_3.setCheckable(True)
        self.btn_strona_glowna_3.setAutoExclusive(True)
        self.btn_strona_glowna_3.setObjectName("btn_strona_glowna_3")
        self.grupa_przyciski_long = QtWidgets.QButtonGroup(MainWindow)
        self.grupa_przyciski_long.setObjectName("grupa_przyciski_long")
        self.grupa_przyciski_long.addButton(self.btn_strona_glowna_3)
        self.verticalLayout_4.addWidget(self.strona_glowna_3)
        self.kalendarz_3 = QtWidgets.QFrame(self.pasek_hover)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kalendarz_3.sizePolicy().hasHeightForWidth())
        self.kalendarz_3.setSizePolicy(sizePolicy)
        self.kalendarz_3.setMinimumSize(QtCore.QSize(185, 85))
        self.kalendarz_3.setMaximumSize(QtCore.QSize(185, 85))
        self.kalendarz_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kalendarz_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kalendarz_3.setObjectName("kalendarz_3")
        self.btn_kalendarz_3 = QtWidgets.QPushButton(self.kalendarz_3)
        self.btn_kalendarz_3.setGeometry(QtCore.QRect(0, 10, 185, 70))
        self.btn_kalendarz_3.setMinimumSize(QtCore.QSize(185, 70))
        self.btn_kalendarz_3.setMaximumSize(QtCore.QSize(185, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_kalendarz_3.setFont(font)
        self.btn_kalendarz_3.setIcon(icon2)
        self.btn_kalendarz_3.setIconSize(QtCore.QSize(40, 40))
        self.btn_kalendarz_3.setCheckable(True)
        self.btn_kalendarz_3.setAutoExclusive(True)
        self.btn_kalendarz_3.setObjectName("btn_kalendarz_3")
        self.grupa_przyciski_long.addButton(self.btn_kalendarz_3)
        self.verticalLayout_4.addWidget(self.kalendarz_3)
        spacerItem1 = QtWidgets.QSpacerItem(183, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.konto_3 = QtWidgets.QFrame(self.pasek_hover)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.konto_3.sizePolicy().hasHeightForWidth())
        self.konto_3.setSizePolicy(sizePolicy)
        self.konto_3.setMinimumSize(QtCore.QSize(185, 85))
        self.konto_3.setMaximumSize(QtCore.QSize(185, 85))
        self.konto_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.konto_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.konto_3.setObjectName("konto_3")
        self.btn_konto_3 = QtWidgets.QPushButton(self.konto_3)
        self.btn_konto_3.setGeometry(QtCore.QRect(0, 10, 185, 70))
        self.btn_konto_3.setMinimumSize(QtCore.QSize(185, 70))
        self.btn_konto_3.setMaximumSize(QtCore.QSize(185, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_konto_3.setFont(font)
        self.btn_konto_3.setIcon(icon3)
        self.btn_konto_3.setIconSize(QtCore.QSize(40, 40))
        self.btn_konto_3.setCheckable(True)
        self.btn_konto_3.setAutoExclusive(True)
        self.btn_konto_3.setObjectName("btn_konto_3")
        self.grupa_przyciski_long.addButton(self.btn_konto_3)
        self.verticalLayout_4.addWidget(self.konto_3)
        self.ustawienia_3 = QtWidgets.QFrame(self.pasek_hover)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ustawienia_3.sizePolicy().hasHeightForWidth())
        self.ustawienia_3.setSizePolicy(sizePolicy)
        self.ustawienia_3.setMinimumSize(QtCore.QSize(185, 85))
        self.ustawienia_3.setMaximumSize(QtCore.QSize(185, 85))
        self.ustawienia_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ustawienia_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ustawienia_3.setObjectName("ustawienia_3")
        self.btn_ustawienia_3 = QtWidgets.QPushButton(self.ustawienia_3)
        self.btn_ustawienia_3.setGeometry(QtCore.QRect(0, 10, 185, 70))
        self.btn_ustawienia_3.setMinimumSize(QtCore.QSize(185, 70))
        self.btn_ustawienia_3.setMaximumSize(QtCore.QSize(185, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_ustawienia_3.setFont(font)
        self.btn_ustawienia_3.setIcon(icon4)
        self.btn_ustawienia_3.setIconSize(QtCore.QSize(40, 40))
        self.btn_ustawienia_3.setCheckable(True)
        self.btn_ustawienia_3.setAutoExclusive(True)
        self.btn_ustawienia_3.setObjectName("btn_ustawienia_3")
        self.grupa_przyciski_long.addButton(self.btn_ustawienia_3)
        self.verticalLayout_4.addWidget(self.ustawienia_3)
        self.wyloguj_3 = QtWidgets.QFrame(self.pasek_hover)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wyloguj_3.sizePolicy().hasHeightForWidth())
        self.wyloguj_3.setSizePolicy(sizePolicy)
        self.wyloguj_3.setMinimumSize(QtCore.QSize(185, 85))
        self.wyloguj_3.setMaximumSize(QtCore.QSize(185, 85))
        self.wyloguj_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wyloguj_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wyloguj_3.setObjectName("wyloguj_3")
        self.btn_wyloguj_3 = QtWidgets.QPushButton(self.wyloguj_3)
        self.btn_wyloguj_3.setGeometry(QtCore.QRect(0, 10, 185, 70))
        self.btn_wyloguj_3.setMinimumSize(QtCore.QSize(185, 70))
        self.btn_wyloguj_3.setMaximumSize(QtCore.QSize(185, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_wyloguj_3.setFont(font)
        self.btn_wyloguj_3.setIcon(icon5)
        self.btn_wyloguj_3.setIconSize(QtCore.QSize(40, 40))
        self.btn_wyloguj_3.setCheckable(True)
        self.btn_wyloguj_3.setAutoExclusive(True)
        self.btn_wyloguj_3.setObjectName("btn_wyloguj_3")
        self.grupa_przyciski_long.addButton(self.btn_wyloguj_3)
        self.verticalLayout_4.addWidget(self.wyloguj_3)
        self.horizontalLayout.addWidget(self.pasek_hover)
        self.pasek_zwiniety = QtWidgets.QFrame(self.centralwidget)
        self.pasek_zwiniety.setMinimumSize(QtCore.QSize(60, 0))
        self.pasek_zwiniety.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pasek_zwiniety.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pasek_zwiniety.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pasek_zwiniety.setObjectName("pasek_zwiniety")
        self.btn_sidebar_zwin_calosc = QtWidgets.QPushButton(self.pasek_zwiniety)
        self.btn_sidebar_zwin_calosc.setGeometry(QtCore.QRect(0, 10, 70, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sidebar_zwin_calosc.sizePolicy().hasHeightForWidth())
        self.btn_sidebar_zwin_calosc.setSizePolicy(sizePolicy)
        self.btn_sidebar_zwin_calosc.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_sidebar_zwin_calosc.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_sidebar_zwin_calosc.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/niebieskie/icons_blue/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("../icons/icons_blue/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_sidebar_zwin_calosc.setIcon(icon6)
        self.btn_sidebar_zwin_calosc.setIconSize(QtCore.QSize(40, 40))
        self.btn_sidebar_zwin_calosc.setCheckable(False)
        self.btn_sidebar_zwin_calosc.setObjectName("btn_sidebar_zwin_calosc")
        self.horizontalLayout.addWidget(self.pasek_zwiniety)
        self.srodek = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srodek.sizePolicy().hasHeightForWidth())
        self.srodek.setSizePolicy(sizePolicy)
        self.srodek.setMinimumSize(QtCore.QSize(0, 0))
        self.srodek.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.srodek.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srodek.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srodek.setObjectName("srodek")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.srodek)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.zawartosc_okna = QtWidgets.QStackedWidget(self.srodek)
        self.zawartosc_okna.setObjectName("zawartosc_okna")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.zawartosc_okna.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.zawartosc_okna.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.zawartosc_okna)
        self.horizontalLayout.addWidget(self.srodek)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_strona_glowna.pressed.connect(self.btn_strona_glowna_3.toggle)
        self.btn_strona_glowna_3.pressed.connect(self.btn_strona_glowna.toggle)
        self.btn_kalendarz.pressed.connect(self.btn_kalendarz_3.toggle)
        self.btn_kalendarz_3.pressed.connect(self.btn_kalendarz.toggle)
        self.btn_konto.pressed.connect(self.btn_konto_3.toggle)
        self.btn_konto_3.pressed.connect(self.btn_konto.toggle)
        self.btn_ustawienia.pressed.connect(self.btn_ustawienia_3.toggle)
        self.btn_ustawienia_3.pressed.connect(self.btn_ustawienia.toggle)
        self.btn_wyloguj.pressed.connect(self.btn_wyloguj_3.toggle)
        self.btn_wyloguj_3.pressed.connect(self.btn_wyloguj.toggle)
        self.btn_sidebar_zwin.pressed.connect(self.btn_sidebar_zwin_calosc.show)
        self.btn_sidebar_zwin.pressed.connect(self.pasek.hide)
        self.btn_sidebar_zwin.pressed.connect(self.pasek_hover.hide)
        self.btn_sidebar_zwin_calosc.pressed.connect(self.pasek_hover.show)
        self.btn_sidebar_zwin_calosc.pressed.connect(self.btn_sidebar_zwin_calosc.hide)
        self.btn_sidebar_zwin_2.pressed.connect(self.pasek_hover.hide)
        self.btn_sidebar_zwin_2.pressed.connect(self.pasek.hide)
        self.btn_sidebar_zwin_2.pressed.connect(self.btn_sidebar_zwin_calosc.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TimeForge"))
        self.btn_strona_glowna.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.btn_kalendarz.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.btn_konto.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.btn_ustawienia.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.btn_wyloguj.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.btn_strona_glowna_3.setText(_translate("MainWindow", "Strona główna"))
        self.btn_strona_glowna_3.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.btn_kalendarz_3.setText(_translate("MainWindow", " Kalendarz     "))
        self.btn_kalendarz_3.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.btn_konto_3.setText(_translate("MainWindow", " Konto          "))
        self.btn_konto_3.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.btn_ustawienia_3.setText(_translate("MainWindow", " Ustawienia    "))
        self.btn_ustawienia_3.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.btn_wyloguj_3.setText(_translate("MainWindow", " Wyloguj się  "))
        self.btn_wyloguj_3.setShortcut(_translate("MainWindow", "Ctrl+Q"))
